title: Ponysdk
description: PonySDK is an open source project and application that uses open source tools built on the Java platform to help you develop Web applications quickly and efficiently
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
